import type { SupportedLocale } from '../../../packages/api-contracts/src';

const en: Record<string, string> = {
  'app.title': 'Furqan',
  'app.loading': 'Loading...',
  'app.contentUnavailable': 'Learning content is unavailable.',
  'app.retry': 'Retry',
  'app.textUnavailable': 'Text unavailable',
  'content.previewIndicator': 'Preview content',
  'nav.home': 'Home',
  'nav.explore': 'Explore',
  'nav.reviews': 'Reviews',
  'nav.profile': 'Profile',
  'nav.menu': 'Menu',
  'nav.closeMenu': 'Close menu',
  'nav.search': 'Search',
  'nav.settings': 'Settings',
  'home.dailyGoal': "Today's goal",
  'home.session': 'Session',
  'home.sessionComplete': 'Daily session complete. Return when you are ready.',
  'home.sessionPending': 'One focused session keeps your Quran habit moving.',
  'home.reviewFirst': 'Strengthen what you learned before starting something new.',
  'home.savedToday': 'Saved for today',
  'home.littleDaily': 'A little every day',
  'home.continue': 'Continue',
  'home.reviewNow': 'Review now',
  'home.explore': 'Explore',
  'home.practice': 'Practice',
  'home.options': 'Options',
  'home.currentLocation': 'Current Quran location',
  'home.locationUnavailable': 'Location unavailable',
  'home.openExplore': 'Open Explore to browse Quran references',
  'home.pageRub': 'Page {page} · Rub {rub}',
  'home.ayah': 'Ayah {ayah}',
  'home.juz': 'Juz',
  'home.hizb': 'Hizb',
  'home.surah': 'Surah',
  'home.learningPath': 'Your learning path',
  'home.quranPath': 'Quran path',
  'home.loadingPath': 'Loading your path...',
  'home.completed': 'Completed',
  'home.reviewDue': 'Review due',
  'home.ready': '{count} ready',
  'home.upToDate': 'Up to date',
  'home.reviewDescription': 'Strengthen what you learned while it is fresh.',
  'home.noReviews': 'No activities are due right now.',
  'home.memorize': 'Memorize',
  'home.choosePath': 'Choose a Quran path to begin memorizing.',
  'home.stories': 'Stories & wisdom',
  'home.storiesDescription': 'Explore source-backed Quran paths, themes, and canonical references.',
  'header.dayStreak': 'Day streak',
  'header.points': 'Points',
  'profile.title': 'Your progress',
  'profile.subtitle': 'A quiet record of your Quran habit.',
  'profile.languageSettings': 'Language and recitation',
  'profile.interfaceLanguage': 'Interface language',
  'profile.lessonLanguage': 'Lesson language',
  'profile.contentLanguage': 'Content language',
  'profile.autoplayRecitation': 'Autoplay recitation',
  'profile.on': 'On',
  'profile.off': 'Off',
  'profile.legal': 'Legal',
  'profile.attributions': 'Sources and attributions',
  'profile.privacy': 'Privacy policy',
  'profile.terms': 'Terms of use',
  'profile.translation': 'Quran translation',
  'profile.script': 'Quran script',
  'profile.reciter': 'Reciter',
  'profile.transliteration': 'Transliteration',
  'profile.show': 'Show',
  'profile.hide': 'Hide',
  'profile.currentPath': 'Current path',
  'profile.choosePath': 'Choose a Quran path',
  'profile.openExplore': 'Open Explore to begin.',
  'profile.dayStreak': 'Day streak',
  'profile.points': 'Points',
  'profile.completedLevels': 'Circles completed',
  'profile.reviewItems': 'Review items',
  'profile.habitSummary': 'Habit summary',
  'profile.longestStreak': 'Longest streak',
  'profile.days': '{count} days',
  'profile.readyReview': 'Ready to review',
  'profile.dailyGoal': 'Daily goal',
  'profile.complete': 'Complete',
  'profile.incomplete': 'Not yet complete',
  'profile.sourcesRights': 'Sources and rights',
  'profile.rightsIntro': 'Production uses only evidence-backed sources. Restricted development resources are identified below.',
  'profile.productionReady': 'Production ready',
  'profile.restricted': 'Restricted',
  'profile.publisherMissing': 'Publisher not recorded',
  'profile.licenseMissing': 'License evidence not recorded',
  'locale.ar': 'Arabic',
  'locale.en': 'English',
  'locale.fr': 'French',
  'lesson.localeUnavailableTitle': 'This lesson is not available in {language}',
  'lesson.localeUnavailableBody': 'Furqan does not mix religious lesson languages. Choose a complete reviewed version to continue.',
  'lesson.switchLanguage': 'Use {language}',
  'lesson.noPublishedAlternative': 'No reviewed alternative is published yet.',
  'lesson.loadingLevel': 'Loading level...',
  'lesson.levelNotFound': 'Level not found.',
  'lesson.backToRoadmap': 'Back to roadmap',
  'lesson.leaveLevel': 'Leave level?',
  'lesson.leaveMessage': 'Completed steps are saved. Your current exercise will restart when you return.',
  'lesson.keepLearning': 'Keep learning',
  'lesson.leave': 'Leave',
  'lesson.progressUnavailable': 'Progress unavailable',
  'lesson.progressRecovered': 'Some saved progress could not be read. Furqan restored a safe copy.',
  'lesson.continue': 'Continue',
  'lesson.completeLevel': 'Complete level',
  'lesson.correctFeedback': 'Correct. Keep this in mind.',
  'lesson.retryFeedback': 'We will revisit this shortly.',
  'lesson.reviewRound': 'Review round: {count} remaining',
  'content.showSources': 'Show sources',
  'content.readMore': 'Read more',
  'content.showLess': 'Show less',
  'content.draftBadge': 'Draft - not for production',
  'content.ayatCount': '{count} ayat',
  'content.revelation.makkah': 'Makkan',
  'content.revelation.madinah': 'Madinan',
  'audio.play': 'Play recitation',
  'audio.pause': 'Pause recitation',
  'audio.restart': 'Restart recitation',
  'audio.repeat': 'Repeat mode: {count} times',
  'audio.speed': 'Playback speed: {speed}',
  'audio.preparing': 'Audio is preparing...',
  'audio.tapToPlay': 'Tap play to start audio',
  'audio.retry': 'Retry audio',
  'completion.loading': 'Loading completion...',
  'completion.levelNotFound': 'Level not found.',
  'completion.progressUnavailable': 'Progress unavailable',
  'completion.alhamdulillah': 'Alhamdulillah!',
  'completion.completed': 'You completed {title}',
  'completion.rewardsEarned': 'Rewards earned',
  'completion.alreadyCounted': 'Already counted earlier',
  'completion.levelCompleted': 'Lesson completed',
  'completion.pathXp': ' +{xp} path XP',
  'completion.saved': 'Completion already saved.',
  'completion.startNextLevel': 'Start next lesson',
  'completion.backToRoadmap': 'Back to roadmap',
  'completion.extraPractice': 'Extra practice',
  'activity.buildAnswer': 'Tap choices to build your answer',
  'activity.selectedAnswer': 'Your answer',
  'activity.matchTranslationHint': 'Tap an ayah segment, then its translation',
  'activity.typeFromMemory': 'Write from memory. Harakat are optional.',
  'activity.typedAnswerLabel': 'Arabic answer from memory',
  'activity.showArabicKeyboard': 'Show Arabic keyboard',
  'activity.hideArabicKeyboard': 'Hide Arabic keyboard',
  'activity.arabicKeyboard': 'Arabic keyboard',
  'activity.keyboardSpace': 'Space',
  'activity.keyboardBackspace': 'Backspace',
  'activity.matchProgress': '{current} of {total} matched',
  'activity.correctFeedback': 'Correct.',
  'activity.incorrectFeedback': 'Not quite. Try again.',
  'question.quiz': 'Quiz',
  'question.checking': 'Checking...',
  'question.tryAgain': 'Try again',
  'question.correct': 'Correct',
  'question.answerIs': 'Answer: {answer}',
  'question.fillAnswer': 'Choose the missing text',
  'question.typeAnswer': 'Type your answer',
  'question.checkMatches': 'Check matches',
  'question.matchHint': 'Match each Arabic word with its meaning',
  'question.true': 'True',
  'question.false': 'False',
  'content.translationUnavailable': 'Translation unavailable in this language.',
  'content.arabicSource': 'Arabic source',
  'content.translationSource': 'Translation source',
  'content.source': 'Source',
  'content.sourceUnavailable': 'Source unavailable',
  'content.unsupported': 'Unsupported content block',
  'content.tafsir': 'Tafsir',
  'content.explanation': 'Explanation',
  'content.wordByWord': 'Word meaning',
  'content.translation': 'Translation',
  'content.listen': 'Listen',
  'content.audioUnavailable': 'Recitation unavailable. Continue the lesson.',
  'roadmap.circle': 'Circle {count}',
  'roadmap.status.completed': 'Completed',
  'roadmap.status.active': 'Current',
  'roadmap.status.available': 'Available',
  'roadmap.status.locked': 'Locked',
  'roadmap.openSurah': 'Open Surah roadmap',
  'roadmap.milestone.intro': 'Surah Intro',
  'roadmap.milestone.context': 'Context',
  'roadmap.milestone.checkpoint': 'Checkpoint',
  'roadmap.milestone.final_review': 'Final Review',
  'roadmap.preview.ayah': 'Ayah {number}',
  'roadmap.preview.start': 'Start',
  'roadmap.preview.continue': 'Continue',
  'roadmap.preview.close': 'Close Ayah preview',
  'roadmap.scrubber.surah': 'Surah roadmap navigation',
  'roadmap.scrubber.ayah': 'Ayah roadmap navigation',
  'search.title': 'Search Quran',
  'search.placeholder': 'Ayah, Arabic text, Surah, or Hizb',
  'search.noResults': 'No Quran results found.',
  'search.localOnly': 'Showing available offline Quran results.',
  'surah.notFound': 'Surah path not found',
  'surah.backHome': 'Back to home',
  'surah.learningPath': 'Surah learning path',
  'surah.progress': '{completed} of {total} lessons complete',
  'surah.introduction': 'Surah introduction',
  'surah.checkpoint': 'Surah checkpoint',
  'surah.segmentCheckpoint': 'Segment checkpoint',
  'surah.ayahRange': 'Ayahs {start}-{end}',
  'levelEntry.title': 'Choose your session',
  'levelEntry.back': 'Back',
  'levelEntry.state.new': 'New lesson',
  'levelEntry.state.in_progress': 'In progress',
  'levelEntry.state.completed': 'Completed',
  'levelEntry.quran': 'Quran passage',
  'levelEntry.session': 'Focused session',
  'levelEntry.minutes': '{count} min',
  'levelEntry.ayat': 'Ayat {start}-{end}',
  'levelEntry.passage': 'Quran passage',
  'levelEntry.start': 'Start lesson',
  'levelEntry.continue': 'Continue lesson',
  'levelEntry.startOver': 'Start over',
  'levelEntry.startOverNote': 'Completed steps and learning history stay saved.',
  'levelEntry.learnAgain': 'Learn again',
  'levelEntry.extraPractice': 'Extra practice',
  'levelEntry.replayNote': 'Replaying does not award duplicate points.',
  'levelEntry.locked': 'Complete the previous circle first.',
  'levelEntry.loadError': 'Session options could not be loaded.',
  'activity.quranPhrase': 'Quran phrase',
  'activity.matchedCorrectly': '{prompt}, matched correctly with {choice}',
  'question.checkAnswer': 'Check answer',
  'discovery.title': 'Quran discovery',
  'discovery.placeholder': 'Al-Fil, 105:1, Juz 30, stories...',
  'discovery.themes': 'Themes',
  'discovery.quranReferences': 'Quran references',
  'discovery.learningPaths': 'Learning paths',
  'discovery.downloadedOnly': 'Downloaded only',
};

const ar: Record<string, string> = {
  'app.title': 'فرقان',
  'app.loading': 'جار التحميل...',
  'app.contentUnavailable': 'محتوى التعلم غير متاح.',
  'app.retry': 'إعادة المحاولة',
  'app.textUnavailable': 'النص غير متاح',
  'content.previewIndicator': 'محتوى تجريبي',
  'nav.home': 'الرئيسية',
  'nav.explore': 'استكشف',
  'nav.reviews': 'المراجعة',
  'nav.profile': 'الحساب',
  'nav.menu': 'القائمة',
  'nav.closeMenu': 'إغلاق القائمة',
  'nav.search': 'البحث',
  'nav.settings': 'الإعدادات',
  'home.dailyGoal': 'هدف اليوم',
  'home.session': 'جلسة',
  'home.sessionComplete': 'اكتملت جلسة اليوم. عد عندما تكون مستعدًا.',
  'home.sessionPending': 'جلسة مركزة تحافظ على عادتك مع القرآن.',
  'home.reviewFirst': 'ثبّت ما تعلمته قبل بدء شيء جديد.',
  'home.savedToday': 'حُفظ لليوم',
  'home.littleDaily': 'قليل دائم كل يوم',
  'home.continue': 'متابعة',
  'home.reviewNow': 'راجع الآن',
  'home.explore': 'استكشف',
  'home.practice': 'تدرب',
  'home.options': 'الخيارات',
  'home.currentLocation': 'موضعك الحالي في القرآن',
  'home.locationUnavailable': 'الموضع غير متاح',
  'home.openExplore': 'افتح الاستكشاف لتصفح مواضع القرآن',
  'home.pageRub': 'الصفحة {page} · الربع {rub}',
  'home.ayah': 'الآية {ayah}',
  'home.juz': 'الجزء',
  'home.hizb': 'الحزب',
  'home.surah': 'السورة',
  'home.learningPath': 'مسار تعلمك',
  'home.quranPath': 'مسار القرآن',
  'home.loadingPath': 'جار تحميل مسارك...',
  'home.completed': 'مكتمل',
  'home.reviewDue': 'مراجعة مستحقة',
  'home.ready': '{count} جاهز',
  'home.upToDate': 'محدّث',
  'home.reviewDescription': 'ثبّت ما تعلمته وهو حاضر في ذهنك.',
  'home.noReviews': 'لا توجد أنشطة مستحقة الآن.',
  'home.memorize': 'الحفظ',
  'home.choosePath': 'اختر مسارًا قرآنيًا لبدء الحفظ.',
  'home.stories': 'قصص وحِكم',
  'home.storiesDescription': 'استكشف مسارات وموضوعات ومراجع قرآنية موثقة.',
  'header.dayStreak': 'أيام الاستمرار',
  'header.points': 'النقاط',
  'profile.title': 'تقدمك',
  'profile.subtitle': 'سجل هادئ لعادتك مع القرآن.',
  'profile.languageSettings': 'اللغة والتلاوة',
  'profile.interfaceLanguage': 'لغة الواجهة',
  'profile.lessonLanguage': 'لغة الدرس',
  'profile.contentLanguage': 'لغة المحتوى',
  'profile.autoplayRecitation': 'تشغيل التلاوة تلقائيًا',
  'profile.on': 'مفعّل',
  'profile.off': 'متوقف',
  'profile.legal': 'قانوني',
  'profile.attributions': 'المصادر ونسب المحتوى',
  'profile.privacy': 'سياسة الخصوصية',
  'profile.terms': 'شروط الاستخدام',
  'profile.translation': 'ترجمة القرآن',
  'profile.script': 'رسم المصحف',
  'profile.reciter': 'القارئ',
  'profile.transliteration': 'النطق بالحروف اللاتينية',
  'profile.show': 'إظهار',
  'profile.hide': 'إخفاء',
  'profile.currentPath': 'المسار الحالي',
  'profile.choosePath': 'اختر مسارًا قرآنيًا',
  'profile.openExplore': 'افتح الاستكشاف للبدء.',
  'profile.dayStreak': 'أيام الاستمرار',
  'profile.points': 'النقاط',
  'profile.completedLevels': 'الحلقات المكتملة',
  'profile.reviewItems': 'عناصر المراجعة',
  'profile.habitSummary': 'ملخص العادة',
  'profile.longestStreak': 'أطول استمرار',
  'profile.days': '{count} يومًا',
  'profile.readyReview': 'جاهز للمراجعة',
  'profile.dailyGoal': 'الهدف اليومي',
  'profile.complete': 'مكتمل',
  'profile.incomplete': 'غير مكتمل بعد',
  'profile.sourcesRights': 'المصادر والحقوق',
  'profile.rightsIntro': 'لا يستخدم الإنتاج إلا مصادر مدعومة بأدلة، وتظهر الموارد التطويرية المقيدة أدناه.',
  'profile.productionReady': 'جاهز للإنتاج',
  'profile.restricted': 'مقيد',
  'profile.publisherMissing': 'الناشر غير مسجل',
  'profile.licenseMissing': 'دليل الترخيص غير مسجل',
  'locale.ar': 'العربية',
  'locale.en': 'الإنجليزية',
  'locale.fr': 'الفرنسية',
  'lesson.localeUnavailableTitle': 'هذا الدرس غير متاح باللغة {language}',
  'lesson.localeUnavailableBody': 'لا يخلط فرقان لغات المحتوى الديني. اختر نسخة كاملة ومراجعة للمتابعة.',
  'lesson.switchLanguage': 'استخدم {language}',
  'lesson.noPublishedAlternative': 'لا يوجد بديل مراجع ومنشور بعد.',
  'lesson.loadingLevel': 'جار تحميل الدرس...',
  'lesson.levelNotFound': 'الدرس غير موجود.',
  'lesson.backToRoadmap': 'العودة إلى المسار',
  'lesson.leaveLevel': 'مغادرة الدرس؟',
  'lesson.leaveMessage': 'تم حفظ الخطوات المكتملة. سيبدأ التمرين الحالي من جديد عند عودتك.',
  'lesson.keepLearning': 'متابعة التعلم',
  'lesson.leave': 'مغادرة',
  'lesson.progressUnavailable': 'التقدم غير متاح',
  'lesson.progressRecovered': 'تعذر قراءة بعض التقدم المحفوظ، فاستعاد فرقان نسخة آمنة.',
  'lesson.continue': 'متابعة',
  'lesson.completeLevel': 'إكمال الدرس',
  'lesson.correctFeedback': 'صحيح. احتفظ بهذا المعنى.',
  'lesson.retryFeedback': 'سنعود إلى هذا لاحقًا.',
  'lesson.reviewRound': 'جولة المراجعة: متبقٍ {count}',
  'content.showSources': 'إظهار المصادر',
  'content.readMore': 'اقرأ المزيد',
  'content.showLess': 'عرض أقل',
  'content.draftBadge': 'مسودة - غير مخصصة للإنتاج',
  'content.ayatCount': '{count} آيات',
  'content.revelation.makkah': 'مكية',
  'content.revelation.madinah': 'مدنية',
  'audio.play': 'تشغيل التلاوة',
  'audio.pause': 'إيقاف التلاوة مؤقتًا',
  'audio.restart': 'إعادة التلاوة',
  'audio.repeat': 'التكرار: {count} مرات',
  'audio.speed': 'سرعة التشغيل: {speed}',
  'audio.preparing': 'جار تجهيز الصوت...',
  'audio.tapToPlay': 'اضغط التشغيل لبدء التلاوة',
  'audio.retry': 'إعادة محاولة الصوت',
  'completion.loading': 'جار تحميل الإكمال...',
  'completion.levelNotFound': 'الدرس غير موجود.',
  'completion.progressUnavailable': 'التقدم غير متاح',
  'completion.alhamdulillah': 'الحمد لله!',
  'completion.completed': 'أكملت {title}',
  'completion.rewardsEarned': 'المكافآت المكتسبة',
  'completion.alreadyCounted': 'تم احتسابه سابقًا',
  'completion.levelCompleted': 'اكتمل الدرس',
  'completion.pathXp': ' +{xp} نقطة للمسار',
  'completion.saved': 'تم حفظ الإكمال سابقًا.',
  'completion.startNextLevel': 'ابدأ الدرس التالي',
  'completion.backToRoadmap': 'العودة إلى المسار',
  'completion.extraPractice': 'تدريب إضافي',
  'activity.buildAnswer': 'اضغط الكلمات لبناء إجابتك',
  'activity.selectedAnswer': 'إجابتك',
  'activity.matchTranslationHint': 'اضغط مقطع الآية ثم ترجمته',
  'activity.typeFromMemory': 'اكتب من الذاكرة. الحركات اختيارية.',
  'activity.typedAnswerLabel': 'الإجابة العربية من الذاكرة',
  'activity.showArabicKeyboard': 'إظهار لوحة المفاتيح العربية',
  'activity.hideArabicKeyboard': 'إخفاء لوحة المفاتيح العربية',
  'activity.arabicKeyboard': 'لوحة المفاتيح العربية',
  'activity.keyboardSpace': 'مسافة',
  'activity.keyboardBackspace': 'حذف',
  'activity.matchProgress': 'تمت مطابقة {current} من {total}',
  'activity.correctFeedback': 'صحيح.',
  'activity.incorrectFeedback': 'ليست صحيحة. حاول مجددًا.',
  'question.quiz': 'اختبار',
  'question.checking': 'جار التحقق...',
  'question.tryAgain': 'حاول مجددًا',
  'question.correct': 'صحيح',
  'question.answerIs': 'الإجابة: {answer}',
  'question.fillAnswer': 'اختر النص الناقص',
  'question.typeAnswer': 'اكتب إجابتك',
  'question.checkMatches': 'تحقق من المطابقة',
  'question.matchHint': 'طابق كل كلمة عربية بمعناها',
  'question.true': 'صحيح',
  'question.false': 'خطأ',
  'content.translationUnavailable': 'الترجمة غير متاحة بهذه اللغة.',
  'content.arabicSource': 'مصدر النص العربي',
  'content.translationSource': 'مصدر الترجمة',
  'content.source': 'المصدر',
  'content.sourceUnavailable': 'المصدر غير متاح',
  'content.unsupported': 'نوع المحتوى غير مدعوم',
  'content.tafsir': 'التفسير',
  'content.explanation': 'الشرح',
  'content.wordByWord': 'معاني الكلمات',
  'content.translation': 'الترجمة',
  'content.listen': 'استمع',
  'content.audioUnavailable': 'التلاوة غير متاحة. تابع الدرس.',
  'roadmap.circle': 'الحلقة {count}',
  'roadmap.status.completed': 'مكتملة',
  'roadmap.status.active': 'الحالية',
  'roadmap.status.available': 'متاحة',
  'roadmap.status.locked': 'مقفلة',
  'roadmap.openSurah': 'فتح مسار السورة',
  'roadmap.milestone.intro': 'مقدمة السورة',
  'roadmap.milestone.context': 'السياق',
  'roadmap.milestone.checkpoint': 'مراجعة مرحلية',
  'roadmap.milestone.final_review': 'المراجعة النهائية',
  'roadmap.preview.ayah': 'الآية {number}',
  'roadmap.preview.start': 'ابدأ',
  'roadmap.preview.continue': 'تابع',
  'roadmap.preview.close': 'إغلاق معاينة الآية',
  'roadmap.scrubber.surah': 'التنقل في مسار السور',
  'roadmap.scrubber.ayah': 'التنقل في مسار الآيات',
  'search.title': 'البحث في القرآن',
  'search.placeholder': 'آية أو نص عربي أو سورة أو حزب',
  'search.noResults': 'لم توجد نتائج قرآنية.',
  'search.localOnly': 'تظهر النتائج القرآنية المتاحة دون اتصال.',
  'surah.notFound': 'مسار السورة غير موجود',
  'surah.backHome': 'العودة إلى الرئيسية',
  'surah.learningPath': 'مسار تعلم السورة',
  'surah.progress': 'اكتمل {completed} من {total} دروس',
  'surah.introduction': 'مقدمة السورة',
  'surah.checkpoint': 'مراجعة السورة',
  'surah.segmentCheckpoint': 'مراجعة المقطع',
  'surah.ayahRange': 'الآيات {start}-{end}',
  'levelEntry.title': 'اختر جلستك',
  'levelEntry.back': 'رجوع',
  'levelEntry.state.new': 'درس جديد',
  'levelEntry.state.in_progress': 'قيد التقدم',
  'levelEntry.state.completed': 'مكتمل',
  'levelEntry.quran': 'المقطع القرآني',
  'levelEntry.session': 'جلسة مركزة',
  'levelEntry.minutes': '{count} د',
  'levelEntry.ayat': 'الآيات {start}-{end}',
  'levelEntry.passage': 'مقطع قرآني',
  'levelEntry.start': 'ابدأ الدرس',
  'levelEntry.continue': 'تابع الدرس',
  'levelEntry.startOver': 'ابدأ من جديد',
  'levelEntry.startOverNote': 'تبقى الخطوات المكتملة وسجل التعلم محفوظين.',
  'levelEntry.learnAgain': 'تعلّم من جديد',
  'levelEntry.extraPractice': 'تدريب إضافي',
  'levelEntry.replayNote': 'إعادة الدرس لا تمنح نقاطًا مكررة.',
  'levelEntry.locked': 'أكمل الحلقة السابقة أولًا.',
  'levelEntry.loadError': 'تعذر تحميل خيارات الجلسة.',
  'activity.quranPhrase': 'عبارة قرآنية',
  'activity.matchedCorrectly': '{prompt}، طابقت بشكل صحيح مع {choice}',
  'question.checkAnswer': 'تحقق من الإجابة',
  'discovery.title': 'استكشاف القرآن',
  'discovery.placeholder': 'الفيل، ١٠٥:١، الجزء ٣٠...',
  'discovery.themes': 'الموضوعات',
  'discovery.quranReferences': 'مواضع القرآن',
  'discovery.learningPaths': 'مسارات التعلم',
  'discovery.downloadedOnly': 'المحتوى المحمل فقط',
};

const fr: Record<string, string> = {
  'app.title': 'Furqan',
  'app.loading': 'Chargement...',
  'app.contentUnavailable': "Le contenu d'apprentissage est indisponible.",
  'app.retry': 'Réessayer',
  'app.textUnavailable': 'Texte indisponible',
  'content.previewIndicator': 'Contenu en aperçu',
  'nav.home': 'Accueil',
  'nav.explore': 'Explorer',
  'nav.reviews': 'Révisions',
  'nav.profile': 'Profil',
  'nav.menu': 'Menu',
  'nav.closeMenu': 'Fermer le menu',
  'nav.search': 'Rechercher',
  'nav.settings': 'Paramètres',
  'home.dailyGoal': "Objectif du jour",
  'home.session': 'Séance',
  'home.sessionComplete': 'Séance du jour terminée. Revenez quand vous le souhaitez.',
  'home.sessionPending': 'Une séance ciblée entretient votre habitude coranique.',
  'home.reviewFirst': "Renforcez l'acquis avant de commencer une nouvelle leçon.",
  'home.savedToday': "Enregistré aujourd'hui",
  'home.littleDaily': 'Un peu chaque jour',
  'home.continue': 'Continuer',
  'home.reviewNow': 'Réviser',
  'home.explore': 'Explorer',
  'home.practice': "S'entraîner",
  'home.options': 'Options',
  'home.currentLocation': 'Position actuelle dans le Coran',
  'home.locationUnavailable': 'Position indisponible',
  'home.openExplore': 'Ouvrez Explorer pour parcourir les références',
  'home.pageRub': 'Page {page} · Rub {rub}',
  'home.ayah': 'Verset {ayah}',
  'home.juz': 'Juz',
  'home.hizb': 'Hizb',
  'home.surah': 'Sourate',
  'home.learningPath': "Votre parcours d'apprentissage",
  'home.quranPath': 'Parcours coranique',
  'home.loadingPath': 'Chargement de votre parcours...',
  'home.completed': 'Terminé',
  'home.reviewDue': 'Révision prévue',
  'home.ready': '{count} prêt(s)',
  'home.upToDate': 'À jour',
  'home.reviewDescription': "Renforcez l'acquis pendant qu'il est récent.",
  'home.noReviews': "Aucune activité n'est prévue maintenant.",
  'home.memorize': 'Mémoriser',
  'home.choosePath': 'Choisissez un parcours coranique pour commencer.',
  'home.stories': 'Récits et sagesses',
  'home.storiesDescription': 'Explorez des parcours, thèmes et références coraniques sourcés.',
  'header.dayStreak': 'Série de jours',
  'header.points': 'Points',
  'profile.title': 'Votre progression',
  'profile.subtitle': 'Un suivi discret de votre habitude coranique.',
  'profile.languageSettings': 'Langue et récitation',
  'profile.interfaceLanguage': "Langue de l'interface",
  'profile.lessonLanguage': 'Langue des leçons',
  'profile.contentLanguage': 'Langue du contenu',
  'profile.autoplayRecitation': 'Lecture automatique',
  'profile.on': 'Activée',
  'profile.off': 'Désactivée',
  'profile.legal': 'Mentions légales',
  'profile.attributions': 'Sources et attributions',
  'profile.privacy': 'Politique de confidentialité',
  'profile.terms': "Conditions d'utilisation",
  'profile.translation': 'Traduction du Coran',
  'profile.script': 'Écriture coranique',
  'profile.reciter': 'Récitateur',
  'profile.transliteration': 'Translittération',
  'profile.show': 'Afficher',
  'profile.hide': 'Masquer',
  'profile.currentPath': 'Parcours actuel',
  'profile.choosePath': 'Choisir un parcours coranique',
  'profile.openExplore': 'Ouvrez Explorer pour commencer.',
  'profile.dayStreak': 'Série de jours',
  'profile.points': 'Points',
  'profile.completedLevels': 'Cercles terminés',
  'profile.reviewItems': 'Éléments à réviser',
  'profile.habitSummary': "Résumé de l'habitude",
  'profile.longestStreak': 'Série la plus longue',
  'profile.days': '{count} jours',
  'profile.readyReview': 'Prêt à réviser',
  'profile.dailyGoal': 'Objectif quotidien',
  'profile.complete': 'Terminé',
  'profile.incomplete': 'Pas encore terminé',
  'profile.sourcesRights': 'Sources et droits',
  'profile.rightsIntro': 'La production utilise uniquement des sources étayées. Les ressources de développement restreintes sont indiquées ci-dessous.',
  'profile.productionReady': 'Prêt pour production',
  'profile.restricted': 'Restreint',
  'profile.publisherMissing': 'Éditeur non renseigné',
  'profile.licenseMissing': 'Preuve de licence non renseignée',
  'locale.ar': 'Arabe',
  'locale.en': 'Anglais',
  'locale.fr': 'Français',
  'lesson.localeUnavailableTitle': "Cette leçon n'est pas disponible en {language}",
  'lesson.localeUnavailableBody': 'Furqan ne mélange pas les langues du contenu religieux. Choisissez une version complète et révisée.',
  'lesson.switchLanguage': 'Utiliser {language}',
  'lesson.noPublishedAlternative': "Aucune version révisée n'est encore publiée.",
  'lesson.loadingLevel': 'Chargement de la leçon...',
  'lesson.levelNotFound': 'Leçon introuvable.',
  'lesson.backToRoadmap': 'Retour au parcours',
  'lesson.leaveLevel': 'Quitter la leçon ?',
  'lesson.leaveMessage': "Les étapes terminées sont enregistrées. L'exercice actuel recommencera à votre retour.",
  'lesson.keepLearning': 'Continuer',
  'lesson.leave': 'Quitter',
  'lesson.progressUnavailable': 'Progression indisponible',
  'lesson.progressRecovered': 'Une partie de la progression était illisible. Furqan a restauré une copie sûre.',
  'lesson.continue': 'Continuer',
  'lesson.completeLevel': 'Terminer la leçon',
  'lesson.correctFeedback': 'Correct. Gardez ceci en mémoire.',
  'lesson.retryFeedback': 'Nous y reviendrons plus tard.',
  'lesson.reviewRound': 'Révision : {count} restant(s)',
  'content.showSources': 'Afficher les sources',
  'content.readMore': 'Lire plus',
  'content.showLess': 'Afficher moins',
  'content.draftBadge': 'Brouillon - hors production',
  'content.ayatCount': '{count} versets',
  'content.revelation.makkah': 'Mecquoise',
  'content.revelation.madinah': 'Médinoise',
  'audio.play': 'Lire la récitation',
  'audio.pause': 'Mettre la récitation en pause',
  'audio.restart': 'Recommencer la récitation',
  'audio.repeat': 'Mode répétition : {count} fois',
  'audio.speed': 'Vitesse de lecture : {speed}',
  'audio.preparing': 'Préparation de l’audio...',
  'audio.tapToPlay': 'Touchez Lecture pour démarrer',
  'audio.retry': 'Réessayer l’audio',
  'completion.loading': 'Chargement de la fin...',
  'completion.levelNotFound': 'Leçon introuvable.',
  'completion.progressUnavailable': 'Progression indisponible',
  'completion.alhamdulillah': 'Alhamdulillah !',
  'completion.completed': 'Vous avez terminé {title}',
  'completion.rewardsEarned': 'Récompenses obtenues',
  'completion.alreadyCounted': 'Déjà comptabilisé',
  'completion.levelCompleted': 'Leçon terminée',
  'completion.pathXp': ' +{xp} XP du parcours',
  'completion.saved': 'Fin déjà enregistrée.',
  'completion.startNextLevel': 'Commencer la leçon suivante',
  'completion.backToRoadmap': 'Retour au parcours',
  'completion.extraPractice': 'Entraînement supplémentaire',
  'activity.buildAnswer': 'Touchez les choix pour construire votre réponse',
  'activity.selectedAnswer': 'Votre réponse',
  'activity.matchTranslationHint': 'Touchez un segment, puis sa traduction',
  'activity.typeFromMemory': 'Écrivez de mémoire. Les signes vocaliques sont facultatifs.',
  'activity.typedAnswerLabel': 'Réponse arabe de mémoire',
  'activity.showArabicKeyboard': 'Afficher le clavier arabe',
  'activity.hideArabicKeyboard': 'Masquer le clavier arabe',
  'activity.arabicKeyboard': 'Clavier arabe',
  'activity.keyboardSpace': 'Espace',
  'activity.keyboardBackspace': 'Effacer',
  'activity.matchProgress': '{current} sur {total} associés',
  'activity.correctFeedback': 'Correct.',
  'activity.incorrectFeedback': 'Pas encore. Réessayez.',
  'question.quiz': 'Quiz',
  'question.checking': 'Vérification...',
  'question.tryAgain': 'Réessayer',
  'question.correct': 'Correct',
  'question.answerIs': 'Réponse : {answer}',
  'question.fillAnswer': 'Choisissez le texte manquant',
  'question.typeAnswer': 'Saisissez votre réponse',
  'question.checkMatches': 'Vérifier les associations',
  'question.matchHint': 'Associez chaque mot arabe à son sens',
  'question.true': 'Vrai',
  'question.false': 'Faux',
  'content.translationUnavailable': 'Traduction indisponible dans cette langue.',
  'content.arabicSource': 'Source arabe',
  'content.translationSource': 'Source de traduction',
  'content.source': 'Source',
  'content.sourceUnavailable': 'Source indisponible',
  'content.unsupported': 'Bloc de contenu non pris en charge',
  'content.tafsir': 'Tafsir',
  'content.explanation': 'Explication',
  'content.wordByWord': 'Sens des mots',
  'content.translation': 'Traduction',
  'content.listen': 'Écouter',
  'content.audioUnavailable': 'Récitation indisponible. Continuez la leçon.',
  'roadmap.circle': 'Cercle {count}',
  'roadmap.status.completed': 'Terminé',
  'roadmap.status.active': 'En cours',
  'roadmap.status.available': 'Disponible',
  'roadmap.status.locked': 'Verrouillé',
  'roadmap.openSurah': 'Ouvrir le parcours de la sourate',
  'roadmap.milestone.intro': 'Introduction',
  'roadmap.milestone.context': 'Contexte',
  'roadmap.milestone.checkpoint': 'Bilan intermédiaire',
  'roadmap.milestone.final_review': 'Révision finale',
  'roadmap.preview.ayah': 'Verset {number}',
  'roadmap.preview.start': 'Commencer',
  'roadmap.preview.continue': 'Continuer',
  'roadmap.preview.close': "Fermer l’aperçu du verset",
  'roadmap.scrubber.surah': 'Navigation dans les sourates',
  'roadmap.scrubber.ayah': 'Navigation dans les versets',
  'search.title': 'Rechercher dans le Coran',
  'search.placeholder': 'Ayah, texte arabe, sourate ou hizb',
  'search.noResults': 'Aucun résultat coranique.',
  'search.localOnly': 'Résultats coraniques hors ligne disponibles.',
  'surah.notFound': 'Parcours de sourate introuvable',
  'surah.backHome': "Retour à l'accueil",
  'surah.learningPath': "Parcours d'apprentissage de la sourate",
  'surah.progress': '{completed} leçons terminées sur {total}',
  'surah.introduction': 'Introduction de la sourate',
  'surah.checkpoint': 'Bilan de la sourate',
  'surah.segmentCheckpoint': 'Bilan du segment',
  'surah.ayahRange': 'Versets {start}-{end}',
  'levelEntry.title': 'Choisissez votre séance',
  'levelEntry.back': 'Retour',
  'levelEntry.state.new': 'Nouvelle leçon',
  'levelEntry.state.in_progress': 'En cours',
  'levelEntry.state.completed': 'Terminée',
  'levelEntry.quran': 'Passage coranique',
  'levelEntry.session': 'Séance ciblée',
  'levelEntry.minutes': '{count} min',
  'levelEntry.ayat': 'Versets {start}-{end}',
  'levelEntry.passage': 'Passage coranique',
  'levelEntry.start': 'Commencer la leçon',
  'levelEntry.continue': 'Continuer la leçon',
  'levelEntry.startOver': 'Recommencer',
  'levelEntry.startOverNote': "Les étapes terminées et l'historique restent enregistrés.",
  'levelEntry.learnAgain': 'Revoir la leçon',
  'levelEntry.extraPractice': 'Exercices supplémentaires',
  'levelEntry.replayNote': 'Rejouer la leçon ne rapporte pas de points supplémentaires.',
  'levelEntry.locked': "Terminez d'abord le cercle précédent.",
  'levelEntry.loadError': 'Impossible de charger les options de séance.',
  'activity.quranPhrase': 'Phrase coranique',
  'activity.matchedCorrectly': '{prompt}, associé correctement à {choice}',
  'question.checkAnswer': 'Vérifier la réponse',
  'discovery.title': 'Explorer le Coran',
  'discovery.placeholder': 'Al-Fil, 105:1, Juz 30, récits...',
  'discovery.themes': 'Thèmes',
  'discovery.quranReferences': 'Références coraniques',
  'discovery.learningPaths': "Parcours d'apprentissage",
  'discovery.downloadedOnly': 'Téléchargé uniquement',
};

const CATALOGS: Record<SupportedLocale, Record<string, string>> = { ar, en, fr };
let currentInterfaceLocale: SupportedLocale = 'en';

export function setCurrentInterfaceLocale(locale: SupportedLocale): void {
  currentInterfaceLocale = locale;
}

export function getCurrentInterfaceLocale(): SupportedLocale {
  return currentInterfaceLocale;
}

export function appText(locale: SupportedLocale, key: string, values: Record<string, string | number> = {}): string {
  const template = CATALOGS[locale][key] ?? en[key];
  if (!template) {
    if (__DEV__) console.warn(`[i18n] Missing UI text: ${locale}:${key}`);
    return CATALOGS[locale]['app.textUnavailable'] ?? en['app.textUnavailable'];
  }
  return Object.entries(values).reduce(
    (text, [name, value]) => text.split(`{${name}}`).join(String(value)),
    template,
  );
}
